import Head from 'next/head'
import { Navigation } from '@/components/Navigation'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <hr />
        <h1>Home</h1>
        <h2>Reproduction steps</h2>
        <ul>
          <li>Click around to see that everything works</li>
          <li>Switch to your terminal</li>
          <li>Run <code>yarn build</code></li>
          <li>Run <code>yarn start</code></li>
          <li>Go back to the page without refreshing it</li>
          <li>Navigate using either the link or button that contains :FAILS</li>
        </ul>
        <p>Result: the request to step1.json returns a 404, and nothing happens</p>
        <p>Wanted: a refresh is triggered, and navigation urls are valid again</p>
        <p>When using any of the other links, the page just refreshes</p>
      </main>
    </>
  )
}
